bookmarks/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('django.contrib.auth.urls')),
    path('users/', include('users.urls')),
    path('images/', include('images.urls', namespace='images')),
    path('', include('pages.urls'))
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls))
    ]
    urlpatterns += (
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )
    

images/urls.py
from django.urls import path

from .views import image_create, image_detail, image_favor, image_list, image_ranking

app_name = 'images'

urlpatterns = [
    path('create/', image_create, name='create'),
    path('detail/<int:id>/<slug:slug>/', image_detail, name='detail'),
    path('favor/', image_favor, name='favor'),
    path('ranking/', image_ranking, name='ranking'),
    path('', image_list, name='list'),
]

pages/urls.py
from django.urls import path

from .views import HomePageView

urlpatterns = [path('', HomePageView.as_view(), name='home')]

images/models.py
from django.db import models
from django.conf import settings
from django.utils.text import slugify
from django.urls import reverse

# Create your models here.
class Image(models.Model):
    title = models.CharField(max_length=360)
    slug = models.SlugField(max_length=360, blank=True)
    url = models.URLField(max_length=360)
    image = models.ImageField(upload_to='images/%Y/%m/%d')
    description = models.TextField(blank=True)
    created = models.DateTimeField(auto_now_add=True, db_index=True)
    uploader = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='uploaded_images', on_delete=models.CASCADE)
    favorited_by = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='favorites', blank=True)
    total_favors = models.PositiveIntegerField(db_index=True, default=0)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("images:detail", args=[self.id, self.slug])
    

images/forms.py
import requests
from urllib.request import urlopen
from django import forms
from django.core.files.base import ContentFile
from django.utils.text import slugify

from .models import Image

class ImageCreateForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ('title', 'url', 'description')
        widgets = {'url': forms.HiddenInput,}

    def clean_url(self):
        url = self.cleaned_data['url']
        allowed_exts = ['jpg', 'jpeg', 'png']
        if not any(ext in url for ext in allowed_exts):
            raise forms.ValidationError(f"Sorry, supported extensions are {', '.join(allowed_exts)}")
        return url

    def save(self, force_insert=False, force_update=False, commit=True):
        image = super().save(commit=False)
        url = self.cleaned_data['url']
        ext = url.rsplit('.', 1)[1].lower()
        image_name = f'{slugify(image.title)}.{ext}'
        content = requests.get(url).content
        image.image.save(image_name, ContentFile(content), save=False)
        if commit:
            image.save()
        return image

images/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.http import JsonResponse, HttpResponse
from django.views.decorators.http import require_POST
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.conf import settings

from common.decorators import ajax_required
from actions.utils import create_action

from .forms import ImageCreateForm
from .models import Image

import redis

r = redis.StrictRedis(host=settings.REDIS_HOST, port=settings.REDIS_PORT, db=settings.REDIS_DB)
# Create your views here.
@login_required
def image_create(request):
    if request.method == 'POST':
        form = ImageCreateForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            new_item = form.save(commit=False)
            new_item.uploader = request.user
            new_item.save()
            messages.success(request, 'Image added successfully.')
            create_action(request.user, 'bookmarked image', new_item)
            return redirect(new_item.get_absolute_url())
    else:
        form = ImageCreateForm(request.GET)
    return render(request, 'images/image/create.html', {'section': 'images', 'form': form})


def image_detail(request, id, slug):
    image = get_object_or_404(Image, id=id, slug=slug)
    total_views = r.incr(f'image:{image.id}:views')
    r.zincrby('image:ranking', 1, image.id)
    return render(request, 'images/image/detail.html', {'section': 'images', 'image': image, 'total_views': total_views})


@ajax_required
@login_required
@require_POST
def image_favor(request):
    image_id = request.POST.get('id')
    action = request.POST.get('action')
    if image_id and action:
        try:
            image = Image.objects.get(id=image_id)
            if action == 'favor':
                image.favorited_by.add(request.user)
                create_action(request.user, 'likes', image)
            else:
                image.favorited_by.remove(request.user)
        except Exception:
            pass
    return JsonResponse({'status': 'ok'})


@login_required
def image_list(request):
    object_list = Image.objects.all()
    paginator = Paginator(object_list, settings.IMAGES_PER_PAGE)
    page = request.GET.get('page')
    try:
        images = paginator.page(page)
    except PageNotAnInteger:
        images = paginator.page(1)
    except EmptyPage:
        if request.is_ajax():
            # stop the ajax
            return HttpResponse('')
        images = paginator.page(paginator.num_pages)
    if request.is_ajax():
        return render(request, 'images/image/list_ajax.html', {'section': 'images', 'images': images})
    return render(request, 'images/image/list.html', {'section': 'images', 'images': images})


@login_required
def image_ranking(request):
    image_ranking = r.zrange('image:ranking', 0, -1, desc=True)[:10]
    image_ranking_ids = [int(id) for id in image_ranking]
    most_viewed_images = list(Image.objects.filter(id__in=image_ranking_ids))
    most_viewed_images.sort(key=lambda x:image_ranking_ids.index(x.id))
    return render(request, 'images/image/ranking.html', {'section': 'images', 'most_viewed_images': most_viewed_images})

templates/images/image/create.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block title %}Bookmark an image{% endblock title %}

{% block content %}
    <h1 class="page-header">Bookmark an image</h1>
    <div class="row">
        <div class="col-md-5">
            <img src="{{request.GET.url}}" class="img-fluid">
        </div>
        <div class="col-md-7">
            <form action="" method="post">
                {% csrf_token %}
                {{form|crispy}}
                <input class="btn btn-success" type="submit" value="Bookmark it!"></input>
            </form>
        </div>
    </div>
{% endblock content %}

templates/images/image/detail.html
{% extends "base.html" %}

{% load thumbnail %}

{% block title %}{{image.title}}{% endblock title %}

{% block content %}
<div class="page-header">
    <h1>{{image.title}}</h1>
</div>
<div class="row">
    <div class="col-md-8">
        {% thumbnail image.image "300" as im %}
        <a href="{{image.image.url}}">
            <img src="{{im.url}}" alt="{{image.title}}">
        </a>
        {% endthumbnail %}
    </div>
    {% with favcount=image.favorited_by.count favorited_by=image.favorited_by.all %}
    <div class="col-md-4">
        <div class="card">
            <div class="card-body">
                <p class="card-text">{{image.description}}</p>
                <a href="#" class="favor btn {% if request.user in favorited_by %}btn-primary{% else %}btn-secondary{% endif %}" data-id="{{image.id}}" data-action="{% if request.user in favorited_by %}un{% endif %}favor">
                    <i class="fa {% if request.user in favorited_by %}fa-heart{% else %}fa-heart-o{% endif %}" aria-hidden="true"></i>
                </a>
                <button class="btn btn-outline-secondary ml-4"><span class="total">{{favcount}}</span> Likes</button>
                <button class="btn btn-outline-secondary ml-4"><span>{{total_views}}</span> Views</button>
            </div>
        </div>
    </div>
    {% endwith %}
</div>
{% endblock content %}

{% block domready %}
$('a.favor').click(e=>{
    e.preventDefault()
    let data = {
        id: e.currentTarget.dataset.id,
        action: e.currentTarget.dataset.action
    }
    $.post('{% url "images:favor" %}', data, data=>{
        if(data.status === 'ok') {
            let previousAction = e.currentTarget.dataset.action
            $('a.favor').attr('data-action', (previousAction === 'favor') ? 'unfavor': 'favor')
            $('a.favor').html((previousAction === 'favor') ? '<i class="fa fa-heart" aria-hidden="true"></i>': '<i class="fa fa-heart-o" aria-hidden="true"></i>')
            $('a.favor').toggleClass('btn-secondary')
            $('a.favor').toggleClass('btn-primary')
            let previousLikes = parseInt($('.total').text())
            $('.total').text((previousAction === 'favor' ? previousLikes + 1: previousLikes - 1))
        }
    })
})
{% endblock domready %}

templates/images/image/list.html
{% extends "base.html" %}

{% block title %}Images bookmarked{% endblock title %}

{% block content %}
    <h1 class="page-header">Images bookmarked <a href="{% url 'images:ranking' %}"><i class="fa fa-trophy" aria-hidden="true"></i></a></h1>
    <div class="row" id="image-list">
        {% include 'images/image/list_ajax.html' %}
    </div>
{% endblock content %}

{% block domready %}
    let page = 1
    let emptyPage = false
    let blockRequest = false

    $(window).scroll(()=>{
        // load the next page when the user is closer than 200 pixels to the bottom of the page
        let margin = $(document).height() - $(window).height() - 200
        if($(window).scrollTop() > margin && emptyPage == false && blockRequest == false) {
            blockRequest = true
            page += 1
            $.get(`?page=${page}`, data=>{
                if(data == ''){
                    emptyPage = true
                } else {
                    blockRequest = false
                    $('#image-list').append(data)
                }
            })
        }
    })
{% endblock domready %}

templates/images/image/list_ajax.html
{% load thumbnail %}

{% for image in images %}
<div class="col-lg-3 col-md-4 col-xs-6 mb-5">
    {% thumbnail image.image "400x300" crop="100%" as im %}
    <a href="{{image.get_absolute_url}}">
        <div class="card" class="d-block mb-4 h-100">
            <img class="card-img-top" src="{{im.url}}" alt="{{image.title}}">
            <div class="card-body">
                <h5 class="card-title" title="{{image.title}}">{{image.title|truncatechars_html:14}}</h5>
            </div>
        </div>
    </a>
    {% endthumbnail %}
</div>
{% endfor %}

templates/images/image/ranking.html
{% extends "base.html" %}

{% block title %}Images ranking{% endblock title %}

{% block content %}
<h1 class="page-header">Images ranking (by view)</h1>
<ul class="list-group ranking">
    {% for image in most_viewed_images %}
        <li class="list-group-item list-group-item-action"><a href="{{image.get_absolute_url}}">{{image.title}}</a></li>
    {% endfor %}
</ul>
{% endblock content %}