bookmarks/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('django.contrib.auth.urls')),
    path('users/', include('users.urls')),
    path('images/', include('images.urls', namespace='images')),
    path('', include('pages.urls'))
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls))
    ]
    urlpatterns += (
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )
    

images/urls.py
from django.urls import path

from .views import image_create, image_detail, image_favor, image_list, image_ranking

app_name = 'images'

urlpatterns = [
    path('create/', image_create, name='create'),
    path('detail/<int:id>/<slug:slug>/', image_detail, name='detail'),
    path('favor/', image_favor, name='favor'),
    path('ranking/', image_ranking, name='ranking'),
    path('', image_list, name='list'),
]

pages/urls.py
from django.urls import path

from .views import HomePageView

urlpatterns = [path('', HomePageView.as_view(), name='home')]

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <title>{% block title %}{% endblock title %} - bookmarks</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Site Logo -->
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}" type="image/x-icon">

    <!-- Bootstrap CSS and font-awesone CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
        crossorigin="anonymous">
    <link href="https://cdn.bootcss.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
        <a class="navbar-brand" href="{% url 'home' %}">Bookmarks</a>
        <button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse" data-target="#collapsibleNavId"
            aria-controls="collapsibleNavId" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="collapsibleNavId">
            <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
                {% if user.is_authenticated %}
                <li class="nav-item {% if section == 'images' %}active{% endif %}"><a class="nav-link" href="{% url 'images:list' %}">Images</a></li>
                <li class="nav-item {% if section == 'dashboard' %}active{% endif %}">
                <li class="nav-item {% if section == 'people' %}active{% endif %}"><a class="nav-link" href="{% url 'user_list'%}">People</a></li>
                    <a href="#" class="nav-link {% if section == 'dashboard' %}active{% endif %} dropdown-toggle" id="userMenu" data-toggle="dropdown" aria-haspopup="true"
                        aria-expanded="false">
                        {{user.username}}
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userMenu">
                        <a href="{% url 'dashboard' %}" class="dropdown-item"><i class="fa fa-user" aria-hidden="true"></i>
                            Dashboard</a>
                        {% if user.is_superuser %}
                        <a href="{% url 'admin:index' %}" class="dropdown-item"><i class="fa fa-database" aria-hidden="true"></i>
                            Admin</a>
                        {% endif %}
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'password_change' %}"><i class="fa fa-lock" aria-hidden="true"></i>
                            Change Password</a>
                        <a class="dropdown-item" href="{% url 'logout' %}"><i class="fa fa-sign-out" aria-hidden="true"></i>
                            Logout</a>
                    </div>
                </li>
                {% else %}
                <li class="nav-item"><a href="{% url 'login' %}" class="btn btn-outline-success">Login</a></li>
                <li class="nav-item"><a href="{% url 'signup' %}" class="btn btn-primary ml-2">Sign up</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <div class="container">

        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-dismissable {% if message.tags %}alert-{{ message.tags }}{% endif %}">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            {{ message }}
        </div>
        {% endfor %}
        {% endif %}

        {% block content %}
        {% endblock content %}


        {% block footer %}
        <footer>
            <p class="float-left">
                <small>&copy;
                    Made by <a href="https://github.com/alphardex" target="_blank">alphardex</a>
                    with <span class="fa fa-heart"></span>
                </small>
            </p>
            <p class="float-right">
                <small><a href="mailto:2582347430@qq.com">Contact</a></small>
            </p>
        </footer>
        {% endblock footer %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
    <script src="https://cdn.bootcss.com/js-cookie/latest/js.cookie.min.js"></script>
    <script>
        let csrftoken = Cookies.get('csrftoken');

        function csrfSafeMethod(method) {
            // these HTTP methods do not require CSRF protection
            return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
        }

        $.ajaxSetup({
            beforeSend: function (xhr, settings) {
                if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                    xhr.setRequestHeader("X-CSRFToken", csrftoken);
                }
            }
        });

        $(document).ready(function(){
        {% block domready %}
        {% endblock %}
        });
    </script>
</body>

</html>